
data:
  raw_path: "data/raw/insurance_data.csv"
  processed_path: "data/processed/cleaned_data.parquet"

eda:
  numeric_threshold: 0.7
  outlier_threshold: 1.5
  min_samples: 10

report:
  output_format: "pdf"
  include_appendix: true
